image: node:latest

variables:
  REGISTRY_NAME: 'registry.gitlab.com'
  IMAGE_NAME: "registry.gitlab.com/${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}"

stages:
  - test

test:
  # install deps
  before_script:
    - cp src/config_sample.js src/config.js
    - yarn
  stage: test
  script:
    - yarn lint:css
    - yarn lint:js

