image: node:latest

variables:
  REGISTRY_NAME: 'registry.gitlab.com'
  IMAGE_NAME: "registry.gitlab.com/${CI_PROJECT_PATH}"

stages:
  - test
  - build

test:
  # install deps
  before_script:
    - cp src/config_sample.js src/config.js
    - yarn
  stage: test
  script:
    - yarn lint:css
    - yarn lint:js

build-uat:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  services:
    - docker:dind
  script:
    - docker build . -t "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}" -t "${IMAGE_NAME}:uat" --build-arg REACT_APP_ENV=uat
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:uat"
  only:
    - master

build-prod:
  image: docker:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  services:
    - docker:dind
  stage: build
  script:
    - docker build . -t "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}" -t "${IMAGE_NAME}:prod"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:prod"
  only:
    - tags
