const UNAUTHENTICATED = 'UNAUTHENTICATED';
const FORBIDDEN = 'FORBIDDEN';
const NOT_FOUND = 'NOT_FOUND';
const INTERNAL_ERROR = 'INTERNAL_ERROR';
const PARAMS_ERROR = 'PARAMS_ERROR';

export {
  UNAUTHENTICATED, FORBIDDEN, NOT_FOUND, INTERNAL_ERROR, PARAMS_ERROR,
};
